_BASE_: "Base-DiffusionInst.yaml"
MODEL:
  MASK_ON: True
  WEIGHTS: "/models/swin_base_patch4_window7_224_22k.pkl"
  BACKBONE:
    NAME: build_swintransformer_fpn_backbone
  SWIN:
    SIZE: B-22k
  FPN:
    IN_FEATURES: ["swin0", "swin1", "swin2", "swin3" ]
  DiffusionInst:
    NUM_PROPOSALS: 500
    NUM_CLASSES: 80
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST:  ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 32 #16
  BASE_LR: 0.00005 #0.000025
  STEPS: (175000, 210000) #(350000, 420000)
  MAX_ITER: 225000 #450000
INPUT:
  CROP:
    ENABLED: True
  FORMAT: "RGB"
