_BASE_: "Base-DiffusionInst.yaml"
MODEL:
  WEIGHTS: "/models/R-50.pkl"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  DiffusionInst:
    NUM_PROPOSALS: 500
    NUM_CLASSES: 80
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST:  ("coco_2017_val",)
SOLVER:
  STEPS: (350000, 420000) #(87500, 105000) #(350000, 420000)
  MAX_ITER: 450000 #112500 #450000
INPUT:
  CROP:
    ENABLED: True
  FORMAT: "RGB"
